## **Numpy**

#### **基本語法**

In [ ]:
import numpy as np

arr = np.array([1,2,3,4,5])  #74. 用列表建立一維陣列
print("Shape:",arr.shape)    #75.  輸出陣列形狀
print("Data Type", arr.dtype) #76. 輸出 元素資料型別
print("Number of dimenssions:" , arr.ndim) #77.輸出維度數量
print("Size:", arr.size) #77. 陣列中元素總數量

# np 提供多種方法建立陣列:
arr0 = np.zeros([])      #77. 建立指定大小陣列0填充
arr1 = np.ones((3,2))     #78. 建立指定大小陣列1.填充
arrfull = np.full((2,3),5)   #79. 建立指定大小陣列指定填充
arrange = np.arange(1,10,4)  #80. 建立等差陣列，指定起始值、終止值、間隔值 (計算個數)
arrlins = np.linspace(5,3.3333,3) #81. 建立等差陣列，指定起始值、終止值、間隔值  (計算間隔)
arrlog = np.logspace(5,100)    #82. 建立等比陣列，指定起始值、終止值、間隔值
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]]) #83. 建立2維陣列
arr_3d  = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])  #83. 建立3維陣列
arr = np.array([1,2,3,4,5])
a = arr[2]            #84.  一維陣列索引
b = arr[1:4]           #85.  一維陣列切片
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
c = arr_2d[1,2]         #86. 二維陣列索引
d = arr_2d[0,:]         #87. 二維陣列 列切片
e = arr_2d[:,0]         #88. 二維陣列 欄切片





print(arr_2d)
arr0
print(arr1)
arrfull
arrange
arrlins
arrlog
print(arr_2d)
arr_3d
print(arr_2d.shape)
print(arr_3d.shape)
print(a)
print(b)
print(c)
print(d)
print(e)




Shape: (5,)
Data Type int64
Number of dimenssions: 1
Size: 5
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
(2, 2, 2)
3
[2 3 4]
6
[1 2 3]
[1 4 7]


#### **基本運算**

##### **四則運算**

In [ ]:
arr_2d1  = np.array([[1,2],[3,4]])
arr_2d2  = np.array([[5,6],[7,8]])

print(arr_2d1 + arr_2d2)    #89. numpy陣列 加法 (對每元素)
print(arr_2d1 - arr_2d2)    #90. numpy陣列 減法 (對每元素)
print(arr_2d1 * arr_2d2)    #91. numpy陣列 乘法 (對每元素)
print(arr_2d1 / arr_2d2)    #92. numpy陣列 加法 (對每元素)


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


##### **統計運算**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])

print(np.sum(arr))                 #93. 求和(統計)
print(np.mean(arr))                 #94. 平均值(means)
print(np.std(arr))                 #95. 標準差(standard deviation)
print(np.max(arr))                 #96. 最大值
print(np.min(arr))                 #97. 最小值



15
3.0
1.4142135623730951
5
1


##### **數學函數運算 (同樣對每個元素計算)**

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])

print(np.exp(arr))                 #98.指數函數
print(np.log(arr))                 #99.對數函數
print(np.log10(arr))                #100. 對數函數(10為底)
print(np.sin(arr))                 #101. 三角函數sin
print(np.cos(arr))                 #102. 三角函數cos

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


##### **排序與搜尋**

In [ ]:
import numpy as np
arr = np.array([2,3,5,4,6])

print(np.sort(arr))                 #103. 排序
print(np.argmax(arr))                #104. 搜索最大索引(取得Index)
print(np.argmin(arr))                #105. 搜索最小索引(取得Index)

[2 3 4 5 6]
4
0


##### **矩陣乘法(線代)**

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print(np.dot(A,B))                  #106. 矩陣乘法

[[19 22]
 [43 50]]


##### **求解方程組(線代)**


In [ ]:
import numpy as np
A = np.array([[3,1],[1,2]])
b = np.array([9,8])

print(np.linalg.solve(A,b))             #107. 求解方程組 結果意味著x = 2 , y = 3

[2. 3.]


##### **廣播機制**

###### **意旨 遇到形狀不同的陣列 較小的陣列會在前面維度補1 使其可以進行元素的運算**

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([1,0,1])

result = A + B
result

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10]])

##### **向量化函數操作**

###### **意旨 針對每一個陣列元素代入函數之函數**

In [ ]:
import numpy as np
arr = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])

sin_arr = np.sin(arr)
print(sin_arr)

cos_arr = np.cos(arr)
print(cos_arr)



[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]


In [ ]:
import numpy as np


def square(x):
  return x**2
v_square = np.vectorize(square)     #108. 自訂函數 向量化操作

arr = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])

s_arr = v_square(arr)

print(s_arr)




[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


## **Pandas**

##### **Series**

In [5]:
import pandas as pd
data = [1,2,3,4,5]
s = pd.Series(data)     #109. 建立pd Series
print(s[0])          #110. Series Index索引
print(s[1:4])         #111. Series 切片
mask = s > 2        #112 Series 布林遮罩
print(s.describe(),"\n")    #113. Series 描述性統計
print(s.sum(),"\n")      #114. Series 總和
print(s * 2)        #115. Series 可以直接乘
print(s[mask])
s




1
1    2
2    3
3    4
dtype: int64
count    5.000000
mean     3.000000
std      1.581139
min      1.000000
25%      2.000000
50%      3.000000
75%      4.000000
max      5.000000
dtype: float64 

15 

0     2
1     4
2     6
3     8
4    10
dtype: int64
2    3
3    4
4    5
dtype: int64


0    1
1    2
2    3
3    4
4    5
dtype: int64

#### **DataFrame**

In [7]:
import pandas as pd

data = {
    'Name':['Alice','Danny','Apple','Arina'],
    'Age':(24 ,25, 26,40),
    'City': ['New York','Taipei','Taipei','Taipei']
}
df = pd.DataFrame(data)                     #116. DataFrame 建立
df

df['Name']                            #117. 輸出DataFrame 欄資料
print(df.loc[0])                         #118. 輸出第一列(從0開始)
print("---")
print(df.iloc[0,1] )                       #119. 輸出第一列第二行的值

Name       Alice
Age           24
City    New York
Name: 0, dtype: object
---
24


In [12]:
print(f"{df.describe()}\n")
print(df['Age'].mean())                      #120. 輸出欄位平均
df.sort_values(by='Age')                      #121. 將欄位進行排序


             Age
count   4.000000
mean   28.750000
std     7.544314
min    24.000000
25%    24.750000
50%    25.500000
75%    29.500000
max    40.000000

28.75


Name  Age      City
0  Alice   24  New York
1  Danny   25    Taipei
2  Apple   26    Taipei
3  Arina   40    Taipei

In [21]:
import pandas as pd
data = pd.read_csv('data.csv')                  #122. 讀取CSV數據
data.head()                             #123. 讀取前5筆資料
data.head(3)                            #124. 讀取前3筆

In [23]:
import pandas as pd
data = pd.DataFrame({'A':[1,2,None,4],
            'B':[None,2,3,4],
            'C':[1,2,4,4]})
print(f"原始數據:\n{data},\n---")

data_drop = data.dropna()                     #125. 刪除包含缺失值的列
data_fill = data.fillna(0)                     #126. 用指定值填充缺失值
data_ffill = data.fillna(method = 'ffill')            #127. 用前一值填充缺失值
data_bfill = data.fillna(method = 'bfill')            #128. 用後一值填充缺失值
data_dup  = data.drop_duplicates()                 #129. 刪除重複值

data_drop
data_fill
data_ffill
data_bfill
data_dup

原始數據:
     A    B  C
0  1.0  NaN  1
1  2.0  2.0  2
2  NaN  3.0  4
3  4.0  4.0  4,
---


<ipython-input-23-cfc1a88e5446>:9: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data_ffill = data.fillna(method = 'ffill')            #127. 用前一值填充缺失值
<ipython-input-23-cfc1a88e5446>:10: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data_bfill = data.fillna(method = 'bfill')            #128. 用後一值填充缺失值


A    B  C
0  1.0  NaN  1
1  2.0  2.0  2
2  NaN  3.0  4
3  4.0  4.0  4

In [25]:
import pandas as pd
data1 = pd.DataFrame({'A':[1,2,3],
            'B':[4,5,6],})
data2 = pd.DataFrame({'A':[1,8,9],
            'B':[10,11,12],})

data_concat = pd.concat([data1,data2], ignore_index=True)    # 130. concat()合併兩資料
data_merge = pd.merge(data1,data2, on='A')

data_concat
data_merge

A  B_x  B_y
0  1    4   10

In [47]:
import pandas as pd
data1 = pd.DataFrame({'A':[4,2,3],
            'B':[4,5,6],})
data2 = pd.DataFrame({'A':['Apple','Banana','Cina'],
            'B':['D','F','G'],})
data3 = pd.DataFrame({'A':[1,2,None,4],
            'B':[None,2,3,4],
            'C':[1,2,4,4]})
df = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
df3 = pd.DataFrame(data3)

In [50]:
df.query('A>1')                          #131. 使用query 篩選
df.where(df>4)                           #132. 選取大於4的數據，其餘NA
df[df['A'].isin([1,3])]                       #133. isin 篩選
df2[df2['A'].str.contains('a')]                   #134.  str篩選
df3.select_dtypes(include='number')                 #135. 用類型篩選
df.sort_values(by ='A')                      #136. 用A欄位的
df.index = ['row3','row1','row4']                 #137. 命名列名稱，並對他排序
print(df.sort_index())

      A  B
row1  2  5
row3  4  4
row4  3  6


In [53]:
import pandas as pd
data = {'category':['A','A','A','B','B','B','C','C','C'],
      'value':[1,2,35,56,77,345,88,99,76]}
df = pd.DataFrame(data)

grouped = df.groupby('category')                 #138. 依照欄位分組
grouped.sum()                            #139. 分組後統計(分組加總)
grouped.mean()                           #140. 分組後統計(分組平均)
grouped.size()                           #141. 分組後統計(分組計數)

category
A    3
B    3
C    3
dtype: int64